name: inbox_alarm
description: inbox_alarm
version: 0.1.2

publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  alarm: ^3.1.3
  supabase_flutter: ^2.0.0
  http: ^0.13.3
  intl: ^0.17.0
  cupertino_icons: ^1.0.2
  firebase_core: ^2.31.0
  flutter:
    sdk: flutter
  permission_handler: ^11.1.0
  weekday_selector: ^1.1.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.1.0

flutter:

  uses-material-design: true

  assets:
    - assets/mozart.mp3
    - assets/nokia.mp3
    - assets/one_piece.mp3
    - assets/star_wars.mp3
    - assets/marimba.mp3